# Numpy beginner's Bootcamp Session-1

## What is Numpy?

### Answer :- Numpy is a linear algebra library for python,which add support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. 

## Why it is needed in the field of DataScience?
### Answer :- Almost all of the PyData ecosystem rely on numpy as one of their building block.

### It has binding with C libray, so it is fast

## Numpy Array

### They are basically 2 types
- Vectors 
- Matrices


## Let's begin our introduction by exploring how to create Numpy arrays.

## Creating Numpy Arrays

### From a Python List

We can create a Numpy array by directly converting a list or list of lists:

In [0]:
import numpy as np


In [3]:
list1 = [10,20,30]
list1

[10, 20, 30]

In [4]:
np.array(list1)

array([10, 20, 30])

In [5]:
type(np.array(list1))

numpy.ndarray

In [6]:
matrix = [[10,20,30],[40,50,60],[70,80,90]]
matrix

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]

In [7]:
np.array(matrix)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

## Built-in Methods

### There are lots of built-in ways to generate Arrays in Numpy.
### Lets discuss some of them.


### arange method

this method returns evenly spaced values within a given interval.

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.arange(0,11,-2)

array([], dtype=int64)

In [11]:
np.arange(0,-11,-2)

array([  0,  -2,  -4,  -6,  -8, -10])

### zeros and ones methods 

This methods are used to generate arrays of zeros or ones

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### linspace method
This method returns evenly spaced numbers over a specified interval.

In [16]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [17]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### eye method

This method used to create an identity matrix

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Array Attributes and Methods

Let's discuss some of the useful attributes and methods of an array:

In [0]:
arr1 = np.arange(36)
arr2 = np.arange(0,100,10)


In [20]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [21]:
arr2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

### max method
This method is used to get the maximum of an array

In [22]:
arr1.max()

35

In [23]:
arr2.max()

90

### min method
This method is used to get the minimum of an array

In [24]:
arr1.min()

0

### argmax and argmin methods
This method are used to find the index of the element with the maximum and minimum value.

In [27]:
arr2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [28]:
arr2.argmax()

9

In [29]:
arr2.argmin()

0

### reshape method
this method returns an array containing the same data with a new shape.

In [30]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [32]:
arr1.shape

(36,)

In [33]:
arr1.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [34]:
arr1.reshape(6,6).shape

(6, 6)

## Numpy Operations

### Arithmetic Operations
You can perform many arithmetic operation on numpy array.
Let's start

In [36]:
arr2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [38]:
arr2+arr2

array([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180])

In [39]:
arr2-arr2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [40]:
arr2*2

array([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180])

In [41]:
arr2*arr2

array([   0,  100,  400,  900, 1600, 2500, 3600, 4900, 6400, 8100])

In [42]:
arr2+2

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [43]:
arr2-2

array([-2,  8, 18, 28, 38, 48, 58, 68, 78, 88])

In [44]:
arr2**2

array([   0,  100,  400,  900, 1600, 2500, 3600, 4900, 6400, 8100])

In [46]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr2/arr2

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [48]:
# Also warning, but not an error instead infinity
1/arr2

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 0.1       , 0.05      , 0.03333333, 0.025     ,
       0.02      , 0.01666667, 0.01428571, 0.0125    , 0.01111111])